name: Publish Release

on:
  pull_request_review:
    types: [submitted]
    branches: [master]

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Release from pull request
      if: github.event.review.state == 'approved'
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: Made release from latest pull request
