name: Publish Release

on:
  push:
    branches:
      - master
    paths:
      - package.json

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Release from merge to master
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: Made release from latest merge request
