name: Publish Release

on:
  push:
    branches:
      - master
    paths:
      - package.json

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Made a new release"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
